# Generated by Django 5.2.12 on 2026-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=150)),
                ('hobby', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('document', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
