# Generated by Django 5.2.12 on 2026-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
